name: eval_3dgen
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py310h3406613_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - arrow-cpp=13.0.0=ha770c72_49_cpu
  - assimp=5.4.2=h2334b4d_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - av=9.1.0=py310h82817de_0
  - aws-c-auth=0.7.22=hbd3ac97_10
  - aws-c-cal=0.7.1=h87b94db_1
  - aws-c-common=0.9.23=h4ab18f5_0
  - aws-c-compression=0.2.18=he027950_7
  - aws-c-event-stream=0.4.2=h7671281_15
  - aws-c-http=0.8.2=he17ee6b_6
  - aws-c-io=0.14.10=h826b7d6_1
  - aws-c-mqtt=0.10.4=hcd6a914_8
  - aws-c-s3=0.6.0=h365ddd8_2
  - aws-c-sdkutils=0.1.16=he027950_3
  - aws-checksums=0.1.18=he027950_7
  - aws-crt-cpp=0.27.3=hda66527_2
  - aws-sdk-cpp=1.11.329=h46c3b66_9
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hef167b5_0
  - boost-cpp=1.84.0=ha9f02ad_7
  - brotli-python=1.1.0=py310hf71b8c6_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cmake=4.1.0=hc85cc9f_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=3.2.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - eigen=3.4.0=h00ab1b0_0
  - embree=3.13.0=habf647b_1
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.3.2=h37c90e5_3
  - flask=3.1.1=pyhd8ed1ab_0
  - fmt=9.1.0=h924138e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - frozenlist=1.7.0=py310h9548a50_0
  - gflags=2.2.2=he1b5a44_1004
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.1.0=h9c3ff4c_2
  - glfw=3.4=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.14=hecca717_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.0.0=h76408a6_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsoncpp=1.9.5=h4bd325d_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libaec=1.1.4=h3f801dc_0
  - libarrow=13.0.0=hbec76fc_49_cpu
  - libblas=3.9.0=31_h59b9bed_openblas
  - libboost=1.84.0=h6c02f8c_7
  - libboost-devel=1.84.0=h1a2810e_7
  - libboost-headers=1.84.0=ha770c72_7
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.8=default_hddf928d_0
  - libclang13=20.1.8=default_ha444ac7_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_4
  - libgoogle-cloud=2.26.0=h26d7fe4_0
  - libgoogle-cloud-storage=2.26.0=ha262f82_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - liblzf=3.6=hb9d3cd8_3
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.64.0=h161d5f1_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.29=ha39b09d_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.5=h27ae623_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libsystemd0=256.9=h2774228_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.7.0=hc4654cb_2
  - libudev1=257.4=h9a4d06a_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb03c661_1
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py310h89163eb_1
  - msgpack-python=1.1.1=py310h3788b33_0
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - narwhals=2.1.1=pyhe01879c_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numpy=1.26.4=py310hb13e2d6_0
  - open3d=0.18.0=py310h657ac02_7
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.2=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=hc749103_2
  - pillow=11.0.0=py310hfeaa1f3_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.4=h54a6638_1
  - plotly=6.3.0=pyhd8ed1ab_0
  - proj=9.5.1=h0054346_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pugixml=1.14=h59595ed_0
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hd6af730_0_cpython
  - python_abi=3.10=2_cp310
  - qhull=2020.2=h434a139_5
  - qt6-main=6.8.3=h6441bc3_1
  - rdma-core=55.0=h5888daf_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=hc2a1206_0
  - requests=2.32.4=pyhd8ed1ab_0
  - retrying=1.4.2=pyhe01879c_0
  - rhash=1.4.6=hb9d3cd8_1
  - s2n=1.4.17=he19d79f_0
  - setuptools=78.1.1=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.50.4=hbc0de68_0
  - tbb=2022.2.0=hb60516a_0
  - tbb-devel=2022.2.0=h74b38a2_0
  - tinyobjloader=1.0.7=h59595ed_2
  - tk=8.6.13=noxft_hd72426e_102
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - ucx=1.16.0=h209287a_5
  - urllib3=2.5.0=pyhd8ed1ab_0
  - utf8proc=2.6.1=h5eee18b_1
  - utfcpp=4.0.6=h005c6e1_0
  - vtk-base=9.3.1=qt_py310h52ece9e_207
  - wayland=1.23.1=h3e06ad9_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - wslink=2.3.4=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yarl=1.20.1=py310h89163eb_0
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.0.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - args==0.1.0
      - asttokens==3.0.0
      - attrdict==2.0.1
      - audioread==3.0.1
      - blender==1.4
      - braceexpand==0.1.7
      - ccimport==0.4.4
      - clint==0.5.1
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cumm-cu121==0.7.11
      - cycler==0.12.1
      - datasets==3.6.0
      - decorator==5.2.1
      - deepspeed==0.15.4
      - defusedxml==0.7.1
      - git+https://github.com/openai/CLIP.git
      - git+https://github.com/graphdeco-inria/diff-gaussian-rasterization.git
      - dill==0.3.8
      - distro==1.9.0
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.18.0
      - fire==0.7.0
      - flash-attn==2.7.2.post1
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - freetype-py==2.5.1
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glcontext==3.0.0
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - groundingdino-py==0.4.0
      - h11==0.14.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.7
      - hjson==3.1.0
      - hpsv2==1.2.0
      - httpcore==0.17.3
      - httpx==0.24.0
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - igraph==0.11.9
      - imageio==2.37.0
      - iniconfig==2.1.0
      - ipdb==0.13.13
      - ipython==8.37.0
      - janus==2.0.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llamafactory==0.9.4.dev0
      - llava==1.7.0.dev0
      - llvmlite==0.44.0
      - lpips==0.1.4
      - markdown-it-py==4.0.0
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelscope==1.28.2
      - moderngl==5.12.0
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.61.2
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - onnxruntime==1.16.3
      - openai==1.102.0
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.2
      - pandas==2.3.1
      - parso==0.8.5
      - pccm==0.4.16
      - peft==0.13.2
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - plyfile==1.1.2
      - pooch==1.8.2
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==13.0.0
      - pybind11==3.0.0
      - pycocotools==2.0.10
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyglet==2.1.9
      - pygments==2.19.2
      - pymatting==1.1.14
      - pymeshfix==0.17.1
      - pyopengl==3.1.0
      - pyparsing==3.2.3
      - pyrender==0.1.45
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvista==0.46.1
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - referencing==0.36.2
      - regex==2025.7.34
      - rembg==2.0.67
      - rich==14.1.0
      - rouge-chinese==1.0.3
      - rpds-py==0.27.0
      - ruff==0.12.8
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - scooby==0.10.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.96
      - sentry-sdk==2.37.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - spconv-cu121==2.3.8
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.47.2
      - supervision==0.6.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - termcolor==3.1.0
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.11.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.49.0
      - trimesh==4.7.3
      - triton==3.2.0
      - trl==0.16.0
      - typer==0.16.0
      - tyro==0.8.14
      - tzdata==2025.2
      - utils3d==0.0.2
      - uvicorn==0.35.0
      - wandb==0.21.3
      - wcwidth==0.2.13
      - webdataset==1.0.2
      - websockets==15.0.1
      - xatlas==0.0.11
      - xxhash==3.5.0
      - yapf==0.43.0
prefix: /mnt/petrelfs/tangyiwen/miniconda3/envs/eval_3dgen
